# Generated by Django 3.0.3 on 2020-02-17 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='firt_name',
            new_name='first_name',
        ),
    ]
